### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by cnphil** [sjtug/mirror-docker#17]
Visiting the page `http://mirrors.sjtug.org/archlinux/` would encounter connection reset, even from China Telecom IPs.

```
philhu@philhu2 ~ $ curl ip.cn
当前 IP：180.168.218.163 来自：上海市 电信
philhu@philhu2 ~ $ curl --verbose http://mirrors.sjtug.org/archlinux/
* Hostname was NOT found in DNS cache
*   Trying 202.120.58.45...
* Connected to mirrors.sjtug.org (202.120.58.45) port 80 (#0)
> GET /archlinux/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: mirrors.sjtug.org
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Enable HTTPS to avoid this?

**Comment by lv-zheng** [comment]
Why reset by peers? Should we study further about the blockage?

**Comment by mrmiywj** [comment]
The same problem happened in HK.

**Comment by lv-zheng** [comment]
We should try to ping and tracepath from different places and find out why

**Comment by htfy96** [comment]
If this is caused by censorship, maybe we have to import Neilpang/le as a submodule and add  
commands to generate certs in `prepare.sh`.

**Comment by htfy96** [comment]
Basic HTTPS support has been implemented on https://mirrors.sjtug.org.
Pending committing changes to this repository.
