### ISSUE TITLE
System Monitor

### ISSUE THREAD

**Issue by htfy96** [sjtug/mirror-docker#18]
We need a system monitor which could analyze logs, watch system status and provide detailed and visualized results.

The basic requirements are:
- CPU/Mem/Net Usage
- Top-X most popular URL

Official docker image would be a plus.

This will be included in `0.1` milestone (Due: May 1, 2016).

**Comment by lv-zheng** [comment]
I am too busy these days LOL.
I think I will contribute if I have time in the next few weeks.
Should we write host program or a program running in another Docker container?

**Comment by htfy96** [comment]
@lv-zheng 
We'd better put it in another Docker container.

**Comment by htfy96** [comment]
Done. https://github.com/htfy96/nginx-simple-watcher .

Pending integration.

**Comment by htfy96** [comment]
Build:

```
docker run -v "$PWD":/usr/src/test -w /usr/src/test  gcc:latest g++ -O2 -std=c++14 watcher.cpp -o watcher -pthread
```

Run:

```
docker run -v "$PWD":/usr/src/test -w /usr/src/test -v /var/log/nginx/mirror/:/var/log/nginx/mirror/ -v /mnt/ftp/mirror-web/_site/:/mnt/site/ -d gcc:latest  ./watcher /var/log/nginx/mirror/access.log 10 /mnt/site/test.json
```

**Comment by htfy96** [comment]
This has been fixed in v2 branch with Prometheus and ELK stack.
