### ISSUE TITLE
使用 mirror 优化 Git 仓库镜像

### ISSUE THREAD

**Issue by liweitianux** [sjtug/mirror-docker#35]
目前的 Git 镜像脚本 ( https://github.com/sjtug/mirror-docker/blob/v2/lug/worker-script/git.sh ) 使用了平常开发模式，会 checkout 一份工作区文件，这个其实没有必要，而且还占用空间。

建议使用 git mirror 方式，只会创建一个 bare 仓库，即只有 `.git` 目录。大致如下：

```bash
#!/bin/sh

set -xe

if [ ! -d "${LUG_path}.git" ]; then
	git clone --mirror "$LUG_origin" "${LUG_path}.git"
fi

cd "${LUG_path}.git"
git remote update --prune
```

参考：
* [How to update a git clone --mirror?](https://stackoverflow.com/a/6151419)
* [What's the difference between git clone --mirror and git clone --bare](https://stackoverflow.com/a/3960063)

**Comment by skyzh** [comment]
新服务器上已经使用了 bare repo，感谢您的提议。老服务器的架构明年应该会进行升级，和新服务器统一。 https://github.com/sjtug/mirror-docker-siyuan/blob/main/lug/worker-script/git.sh

**Comment by liweitianux** [comment]
赞！那么我把这个 issue 关闭了。多谢回复。
