### ISSUE TITLE
Several improvements and suggestions

### ISSUE THREAD

**Issue by lv-zheng** [sjtug/mirror-docker#4]
Avoid installing or using git in container to make the image smaller.

===== original text =====
According to the official Dockerfile docs,
- there should be no `apt-get upgrade`'s
- `apt-get update` and `install` should be placed in a single `RUN` command
- avoid unnecessary installations such as editors
- there shouldn't be too many layers

Also, I have several suggestions
- place mirror root at /mnt/mirrors for possible additional mount points in the future
- avoid using git in container. Use host `.tar.gz` files at build time instead. A host script can be written for grabbing  the latest version of tunasync and mirror-web from github and pack them into `.tar.gz` files.

These changes are under development. I'll make PR tonight. Discussions and 批判一番s are strongly encouraged.

**Comment by Endle** [comment]
> there should be no apt-get upgrade's

这个不太理解，请问能附上一个参考链接吗？

> apt-get update and install should be placed in a single RUN command

最终版本应该合并。现在还是 beta 版本，分开写的话可以充分利用之前的缓存

> avoid unnecessary installations such as editors

现在这么写是为了调试方便吧，同样，release的时候会删去 （会吧 @htfy96 ）

> there shouldn't be too many layers
> 
> place mirror root at /mnt/mirrors for possible additional mount points in the future

我双手赞成

> avoid using git in container. Use host .tar.gz files at build time instead. A host script can be written for grabbing the latest version of tunasync and mirror-web from github and pack them into .tar.gz files.

这个问题我想过，我也觉得应该把 git 的操作剥离出来。不知道 @htfy96 赞同这个 idea 吗？另外，bundle install 等操作是否依赖 git？如果不依赖，能不能把 git 相关的包从 Dockerfile 中删去？

**Comment by lv-zheng** [comment]
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
covers the first 4 suggestions

**Comment by Endle** [comment]
谢谢，那看来这部分内容回头要删掉

2016-04-05 19:22 GMT+08:00 Lv Zheng notifications@github.com:

> https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/sjtug/mirror-docker/issues/4#issuecomment-205761830

## 

Have a nice day!
Zhenbo Li

**Comment by htfy96** [comment]
@lv-zheng 
前面的想法和 @Endle 相同，更改挂载点我也同意。我也很想把docker做得小一点，但是问题是：
- jekyll和tunasync只能通过文件更新的形式通知，这使得分离jekyll和tunasync非常困难
- 依赖关系混乱 出于效率我们希望尽可能多的包从官方源安装而不是自己build，但前端和后端都有大量的`Gemfile`、`requirements.txt`，这造成了冲突

**Comment by lv-zheng** [comment]
host把`tunasync.tar.gz`和`mirror-web.tar.gz`准备好，用`ADD`替换`RUN git`，容器虽然还要编译，但是就可以少装一个git，并且换tunasync和mirror-web也方便。
我担心这样做，会不会在docker hub出问题？

**Comment by Endle** [comment]
> jekyll和tunasync只能通过文件更新的形式通知，这使得分离jekyll和tunasync非常困难

我觉得没必要分离（虽然分离开会优雅很多）。我觉得分离的话就有点过度设计了

> 依赖关系混乱 出于效率我们希望尽可能多的包从官方源安装而不是自己build，但前端和后端都有大量的Gemfile、requirements.txt，这造成了冲突
> 我觉得这没什么关系。如果把所有的依赖整理到若干个 requirements.txt 里，那整体的逻辑还是很清晰的

现阶段，是不是先看看 Issue #5？

> host把tunasync.tar.gz和mirror-web.tar.gz准备好，用ADD替换RUN git

这么做我觉得问题不大

> 我担心这样做，会不会跟docker hub矛盾？

不太懂，能解释一下吗？

**Comment by lv-zheng** [comment]
@Endle 
Does Docker hub have any requirement that an image should be able to be built with a single command `docker build` without additional pre-build commands?

**Comment by Endle** [comment]
> Does Docker hub have any requirement that an image should be able to be built with a single command docker build without additional post-build commands?

为什么我们非要用 Docker Hub 自动构建呢？我们本地构建好后上传不行吗？

**Comment by lv-zheng** [comment]
> 为什么我们非要用 Docker Hub 自动构建呢？我们本地构建好后上传不行吗？

OK，那么这个issue的任务暂定为“避免container中git的使用”。实现了就可以close了。

**Comment by htfy96** [comment]
Implemented by #11
