### ISSUE TITLE
Remove dirty workaround

### ISSUE THREAD

**Issue by Endle** [sjtug/mirror-docker#5]
https://github.com/sjtug/mirror-docker/blob/master/Dockerfile#L51

`RUN sed -i "s/^[ \t]*string.encode('UTF-8')/return string/g" /usr/lib/ruby/vendor_ruby/execjs/encoding.rb`

这是 tuna 的问题，还是更上游的问题？

**Comment by htfy96** [comment]
上游问题

**Comment by htfy96** [comment]
现在用的ubuntu:xenial其实是final beta版本，但是考虑到它是LTS，并且包版本比较新，将于4月21日发布正式版等原因还是采用了其作为底包

**Comment by htfy96** [comment]
If it is fixed by #11 , this issue together with #3 will be closed.

**Comment by Endle** [comment]
> If it is fixed by #11 , this issue together with #3 will be closed.

这个 dirty hack 还是存在的，所以还没到 close issue 的时候

**Comment by htfy96** [comment]
Fixed by v2 branch
